### ISSUE TITLE
Please finish all tasks of week 2

### ISSUE THREAD

**Issue by DLND8** [severin123456/cma-week-2#1]
Please finish all the tasks of week 2 and upload them to GIthub.

**Comment by severin123456** [comment]
You mean the unfinished Plots of Task 4? Or don't you find Task 6?

**Comment by DLND8** [comment]
Yes, please try to finish task 4  and also complete tasks 6, 7.

**Comment by severin123456** [comment]
I uploaded 6 and 7...but im not so sure with all this stuff and already very busy...dont you upload the solutions on https://computationalmovementanalysis.github.io/FS23/ as in Excercise 1?

**Comment by severin123456** [comment]
I think its avout geom_path that i had problems with Task 4 but I have to solve a lot very important and urgent thinks for my DD in Norway and my PWRG2 and this weekend starts my CAS so I don't know if I can work on it...

**Comment by DLND8** [comment]
Yes we will upload the solution soon. Thanks for uploading task 6 and 7. You can consider exercise 2 as done 👍

**Comment by severin123456** [comment]
Thanks
